# Generated by Django 4.1.3 on 2022-12-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=300)),
                ('decs', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
