# Generated by Django 4.1.3 on 2022-12-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='decs',
            new_name='desc',
        ),
    ]
