# Generated by Django 4.1.3 on 2022-12-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_decs_contact_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
    ]
