# Generated by Django 4.1.3 on 2022-12-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_phone_orders_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
