# Generated by Django 4.1.3 on 2022-12-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_orders_address2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='itmes_json',
            new_name='items_json',
        ),
    ]
